--
-- Phase 3 — input layer + RoomClock.
--
-- Fixtures generated by colyseus-0.18 PORTING/generate-input-fixtures.cts
-- (self-verified against the JS schema InputEncoder/InputDecoder, the real
-- InputHandleImpl and RoomClockImpl). Contract:
-- PORTING/sdk-ports-input-layer.md.
--
local schema = require 'colyseus.serializer.schema.schema'
local InputEncoder = require 'colyseus.serializer.schema.input_encoder'
local InputHandle = require 'colyseus.input_handle'
local RoomClock = require 'colyseus.room_clock'
local Room = require 'colyseus.room'
local utils = require 'colyseus.utils.utils'

local MoveInput = schema.define({
  ["vx"] = "number",
  ["vy"] = "number",
  ["jump"] = "boolean",
  ["action"] = "uint8",
  ["_fields_by_index"] = { "vx", "vy", "jump", "action" },
})

local function new_move_input()
  local instance = MoveInput:new()
  instance.vx = 0
  instance.vy = 0
  instance.jump = false
  instance.action = 0
  return instance
end

local function assert_bytes(expected, actual)
  assert_equal(table.concat(expected, ","), table.concat(actual, ","))
end

--- Stub connection capturing sent frames as byte arrays.
local function stub_connection()
  local stub = { state = "OPEN", sent = {} }
  function stub:send(data)
    local bytes = {}
    for i = 1, #data do bytes[i] = data:byte(i) end
    table.insert(self.sent, bytes)
  end
  return stub
end

--- Clock stub with scripted readings.
local function stub_clock()
  local clock = RoomClock.new()
  clock.server_now_value = 0
  clock.last_server_time_value = 0
  clock.smoothed_rtt_value = 0
  function clock:server_now() return self.server_now_value end
  function clock:last_server_time() return self.last_server_time_value end
  function clock:smoothed_rtt() return self.smoothed_rtt_value end
  return clock
end

local function make_handle(clock, mode, opts)
  opts = opts or {}
  local instance = new_move_input()
  local encoder = InputEncoder.new(instance, mode, 3)
  local stub = stub_connection()
  local handle = InputHandle.new(instance, encoder, {
    stamp_render = opts.stamp_render,
    stamp_reckon = opts.stamp_reckon,
    render_delay = opts.render_delay,
    allow_rewind = opts.allow_rewind,
  }, function() return stub end, function() return clock end)
  return handle, stub, instance
end

return function()
  describe("input layer + RoomClock", function()

    it("InputEncoderReliable", function()
      local input = new_move_input()
      local enc = InputEncoder.new(input)

      input.vx = 1.5; input.vy = -2; input.jump = true; input.action = 3
      assert_bytes({128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3}, enc:encode())

      input.vx = 2.5
      assert_bytes({128, 202, 0, 0, 32, 64}, enc:encode())

      -- no change → empty body
      assert_bytes({}, enc:encode())

      input.jump = false; input.action = 7
      assert_bytes({130, 0, 131, 7}, enc:encode())

      -- reset → full snapshot of populated fields
      enc:reset()
      assert_bytes({128, 202, 0, 0, 32, 64, 129, 254, 130, 0, 131, 7}, enc:encode())
    end)

    it("InputEncoderUnreliable", function()
      local input = new_move_input()
      local enc = InputEncoder.new(input, "unreliable", 3)

      input.vx = 1.5; input.vy = -2; input.jump = true; input.action = 3
      assert_bytes({1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3}, enc:encode())
      assert_equal(1, enc.seq)

      input.vx = 2.5
      assert_bytes({1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3, 6, 128, 202, 0, 0, 32, 64}, enc:encode())

      -- no change → carry-forward empty slot, ring re-emitted
      assert_bytes({1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3, 6, 128, 202, 0, 0, 32, 64, 0}, enc:encode())

      input.vy = 9
      assert_bytes({2, 6, 128, 202, 0, 0, 32, 64, 0, 2, 129, 9}, enc:encode())
      assert_equal(4, enc.seq)
    end)

    it("HandleReliableNoStamp", function()
      local handle, stub, input = make_handle(stub_clock())

      input.vx = 1.5; input.vy = -2; input.jump = true; input.action = 3
      assert_equal(1, handle:send())
      input.vx = 2.5
      assert_equal(2, handle:send())
      assert_equal(3, handle:send()) -- no change → body-less [19]

      assert_equal(3, handle.sent_count)
      assert_bytes({19, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3}, stub.sent[1])
      assert_bytes({19, 128, 202, 0, 0, 32, 64}, stub.sent[2])
      assert_bytes({19}, stub.sent[3])
    end)

    it("HandleReliableStampedBoth", function()
      local clock = stub_clock()
      clock.last_server_time_value = 500 -- synced
      clock.smoothed_rtt_value = 80
      local handle, stub, input = make_handle(clock, nil, {
        stamp_render = true, stamp_reckon = true, render_delay = 50,
      })

      clock.server_now_value = 1000
      input.vx = 1.5
      handle:send()
      clock.server_now_value = 1016.7
      input.vx = 2
      handle:send()
      clock.server_now_value = 1033.4
      handle:send()

      -- [19|0x80][varint Δreckon][uint16 renderDelta=90][delta body]
      assert_bytes({147, 205, 232, 3, 90, 0, 128, 202, 0, 0, 192, 63}, stub.sent[1])
      assert_bytes({147, 17, 90, 0, 128, 2}, stub.sent[2])
      assert_bytes({147, 16, 90, 0}, stub.sent[3])

      assert_equal(1000, handle:reckon_time_at(1))
      assert_equal(1017, handle:reckon_time_at(2))
      assert_equal(1033, handle:reckon_time_at(3))
    end)

    it("HandleReliableStampedRenderOnly", function()
      local clock = stub_clock()
      clock.last_server_time_value = 500
      clock.smoothed_rtt_value = 80
      local handle, stub, input = make_handle(clock, nil, {
        stamp_render = true, render_delay = 50,
      })

      clock.server_now_value = 1000
      input.vx = 1.5
      handle:send()     -- stamp = 1000-90 = 910
      clock.server_now_value = 1050
      input.vx = 2
      handle:send()     -- Δ = 50

      assert_bytes({147, 205, 142, 3, 128, 202, 0, 0, 192, 63}, stub.sent[1])
      assert_bytes({147, 50, 128, 2}, stub.sent[2])
      assert_equal(0, handle:reckon_time_at(1)) -- reckon ring off
    end)

    it("HandleUnstampedBeforeSync", function()
      local clock = stub_clock()
      clock.server_now_value = 1234
      clock.last_server_time_value = 0 -- NOT synced
      clock.smoothed_rtt_value = 80
      local handle, stub, input = make_handle(clock, nil, {
        stamp_render = true, stamp_reckon = true,
      })

      input.vx = 1
      handle:send()
      assert_bytes({147, 0, 0, 0, 128, 1}, stub.sent[1])
    end)

    it("HandleAllowRewindGate", function()
      local clock = stub_clock()
      clock.last_server_time_value = 500
      local handle, stub, input = make_handle(clock, nil, {
        stamp_reckon = true,
        allow_rewind = function(d) return d.jump == true end,
      })

      clock.server_now_value = 1000
      input.vx = 1
      handle:send()                     -- unstamped (jump=false at default)
      clock.server_now_value = 1100
      input.jump = true
      handle:send()                     -- stamped, Δ=1100
      clock.server_now_value = 1200
      input.jump = false
      handle:send()                     -- unstamped (baseline holds)
      clock.server_now_value = 1300
      input.jump = true
      handle:send()                     -- stamped, Δ=200

      assert_bytes({19, 128, 1}, stub.sent[1])
      assert_bytes({147, 205, 76, 4, 130, 1}, stub.sent[2])
      assert_bytes({19, 130, 0}, stub.sent[3])
      assert_bytes({147, 204, 200, 130, 1}, stub.sent[4])
    end)

    it("HandleUnreliable", function()
      local clock = stub_clock()
      clock.last_server_time_value = 500
      local handle, stub, input = make_handle(clock, "unreliable", { stamp_reckon = true })

      input.vx = 1.5
      assert_equal(1, handle:send())
      input.vx = 2.5
      assert_equal(2, handle:send())
      assert_equal(2, handle.sent_count)

      -- [20][baseSeq][len][slot]… — unreliable is never stamped
      assert_bytes({20, 1, 6, 128, 202, 0, 0, 192, 63}, stub.sent[1])
      assert_bytes({20, 1, 6, 128, 202, 0, 0, 192, 63, 6, 128, 202, 0, 0, 32, 64}, stub.sent[2])
    end)

    it("HandleAckRtt", function()
      local NOW = 0
      local original_now = RoomClock.get_now
      RoomClock.get_now = function() return NOW end

      local ok, err = pcall(function()
        local handle, stub, input = make_handle(stub_clock())

        NOW = 1000; input.vx = 1; handle:send()
        NOW = 1016; input.vx = 2; handle:send()
        NOW = 1033; input.vx = 3; handle:send()

        NOW = 1080
        assert_equal(80, handle:ack_input(1))
        assert_equal(-1, handle:ack_input(1)) -- stale
        NOW = 1120
        assert_equal(87, handle:ack_input(3)) -- skips 2
        assert_equal(3, handle.last_processed)
        assert_equal(0, handle:pending_count())

        -- replay ring: pending inputs readable until acked
        NOW = 1200; input.vx = 4; handle:send() -- seq 4
        assert_equal(4, handle:at(4).vx)
        assert_equal(nil, handle:at(3))         -- acked → gone

        -- reset: epoch++, fresh counters, next send = full snapshot
        local epoch_before = handle.epoch
        handle:reset()
        assert_equal(epoch_before + 1, handle.epoch)
        assert_equal(0, handle.sent_count)
        NOW = 1300; input.vx = 5
        assert_equal(1, handle:send())
        assert_bytes({19, 128, 5, 129, 0, 130, 0, 131, 0}, stub.sent[#stub.sent])
        NOW = 1360
        assert_equal(60, handle:ack_input(1))
      end)

      RoomClock.get_now = original_now
      if not ok then error(err, 0) end
    end)

    it("RoomClockSamples", function()
      local NOW = 0
      local original_now = RoomClock.get_now
      RoomClock.get_now = function() return NOW end

      local ok, err = pcall(function()
        local clock = RoomClock.new()
        clock:set_patch_interval(50)

        -- (tNow, sNow, rtt) → (offset, rtt, smoothedRtt, jitter, lastServerTime)
        local script = {
          {1000, 500, -1,   -500, 0, 0, 0, 500},
          {1050, 550, 80,   -496, 80, 80, 0, 550},
          {1100, 600, 84,   -492.20000000000005, 84, 80.4, 0, 600},
          {1155, 655, 90,   -488.4800000000001, 90, 81.36000000000001, 0.3125, 655},
          {1205, 705, 76,   -485.83200000000005, 76, 80.82400000000001, 0.29296875, 705},
          {1305, 805, 82,   -483.14880000000005, 82, 80.94160000000002, 0.274658203125, 805},
          {1655, 1155, 78,  -480.93392000000006, 78, 80.64744000000002, 0.274658203125, 1155},
          {1705, 1205, 400, -480.93392000000006, 78, 80.64744000000002, 0.2574920654296875, 1205},
          {1755, 1255, 74,  -479.1405280000001, 74, 79.98269600000002, 0.24139881134033203, 1255},
        }
        for _, row in ipairs(script) do
          NOW = row[1]
          clock:sample(row[2], row[3])
          assert_equal(row[4], clock._clock_offset)
          assert_equal(row[5], clock:rtt())
          assert_equal(row[6], clock:smoothed_rtt())
          assert_equal(row[7], clock:jitter())
          assert_equal(row[8], clock:last_server_time())
        end

        NOW = 1800
        assert_equal(1320.8594719999999, clock:server_now())

        -- render_now — 1e-6 tolerance (exp() ULP variance across libms)
        NOW = 1800
        local r1 = clock:render_now()
        NOW = 1816
        local r2 = clock:render_now()
        NOW = 1816.2
        local r3 = clock:render_now() -- same frame → unchanged
        assert_equal(true, math.abs(r1 - 1320.8594719999999) < 1e-6)
        assert_equal(true, math.abs(r2 - 1336.8594719999999) < 1e-6)
        assert_equal(r2, r3)

        -- reset clears estimates; patch_interval is config and survives
        clock:reset()
        assert_equal(0, clock:smoothed_rtt())
        assert_equal(0, clock:last_server_time())
        assert_equal(50, clock:patch_interval())
      end)

      RoomClock.get_now = original_now
      if not ok then error(err, 0) end
    end)

    it("RoomClockGateWarmup", function()
      local NOW = 0
      local original_now = RoomClock.get_now
      RoomClock.get_now = function() return NOW end

      local ok, err = pcall(function()
        local clock = RoomClock.new()
        clock:set_patch_interval(50)
        local t_now = 1000
        local expected = {
          [5]  = {-341.855, 116.29},
          [10] = {-332.85995895, 134.28008210000002},
          [15] = {-331.7339771603856, 136.53204567922904},
          [20] = {-326.88359617343616, 146.23280765312796},
          [25] = {-328.20499470445236, 143.59001059109553},
          [30] = {-324.79976732303214, 150.40046535393603},
          [35] = {-331.6290303784904, 146.0509707868457},
        }
        for i = 1, 35 do
          t_now = t_now + 50
          NOW = t_now
          local rtt = (i % 2 == 0) and 200 or 100
          clock:sample(t_now - 400, rtt)
          if expected[i] ~= nil then
            assert_equal(expected[i][1], clock._clock_offset)
            assert_equal(expected[i][2], clock:smoothed_rtt())
          end
        end
      end)

      RoomClock.get_now = original_now
      if not ok then error(err, 0) end
    end)

    it("RoomInputOptionsAndTimedRouting", function()
      -- JOIN_ROOM fixture with INPUT_REFLECTION + INPUT_OPTIONS sections
      -- (flags FIXED|PATCH|SUB, tickRate 20, patchRate 50, subSteps 2) —
      -- from PORTING/generate-phase0-fixtures.cts.
      local room = Room.new("phase0")
      room.room_id = "phase0"
      room.connection = stub_connection()
      function room.connection.on() end
      function room.connection.off() end

      room:_on_batch_message(utils.byte_array_to_string({10, 6, 116, 111, 107, 49, 50, 51, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114, 1, 47, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 161, 120, 129, 166, 110, 117, 109, 98, 101, 114, 255, 5, 128, 161, 121, 129, 166, 110, 117, 109, 98, 101, 114, 2, 4, 14, 20, 50, 2}))

      assert_equal(50, room.clock:patch_interval())

      -- no explicit type: the class is synthesized from INPUT_REFLECTION
      local handle = room:input()
      assert_equal(20, handle.tick_rate)
      assert_equal(50, handle.patch_rate)
      assert_equal(2, handle.sub_steps)
      assert_equal(0.05, handle.step_seconds)
      assert_equal(0.025, handle.sub_step_seconds)
      assert_equal(true, handle.replay_buffer_size >= 64)

      -- same handle on later calls
      assert_equal(handle, room:input())

      -- the synthesized input schema has the server's fields (x, y)
      handle.data.x = 4.5
      handle.data.y = 2
      handle:send()

      -- TIMED heartbeat patch [15|0x80][u32 sNow=750][u32 inputSeq=0]
      room:_on_batch_message(utils.byte_array_to_string({143, 238, 2, 0, 0, 0, 0, 0, 0}))
      assert_equal(750, room.clock:last_server_time())
    end)

  end)
end
