local utils = require 'colyseus.utils.utils'

require 'colyseus.room'

--
-- 0.18 wire-compat (Phase 0) — room-level protocol frames.
--
-- Fixtures below generated by colyseus-0.18
-- PORTING/generate-phase0-fixtures.cts (self-verified against the JS
-- packages/sdk Room). See PORTING/sdk-coverage-plan-0.18.md.
--
-- The room is exercised through a stub connection + stub serializer: Phase 0
-- is pure room-layer framing (modifier bits, JOIN_ROOM sections,
-- request/response) — schema decoding has its own suite.
--
return function()

  local function make_room()
    local room = Room.new("phase0")
    room.room_id = "phase0"

    local sent = {}
    room.connection = {
      state = "OPEN",
      send = function(_, data) table.insert(sent, data) end,
    }

    -- records the calls the room makes into the serializer layer
    local calls = { handshake = {}, set_state = {}, patch = {} }
    room.serializer = {
      handshake = function(_, bytes, it) table.insert(calls.handshake, { len = #bytes, offset = it.offset }) end,
      set_state = function(_, bytes, it) table.insert(calls.set_state, { len = #bytes, offset = it.offset }) end,
      patch = function(_, bytes, it) table.insert(calls.patch, { len = #bytes, offset = it.offset }) end,
      get_state = function(_) return nil end,
    }

    local feed = function(frame)
      room:_on_message(utils.byte_array_to_string(frame), { offset = 1 })
    end

    return room, sent, calls, feed
  end

  describe("room protocol (0.18 wire compat)", function()

    it("JoinRoomFullHandshake", function()
      local room, sent, calls, feed = make_room()

      local joins = 0
      room:on("join", function() joins = joins + 1 end)

      -- JOIN_ROOM with length-prefixed state reflection (71 bytes) +
      -- INPUT_REFLECTION and INPUT_OPTIONS tagged sections
      feed({ 10, 6, 116, 111, 107, 49, 50, 51, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114, 1, 47, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 161, 120, 129, 166, 110, 117, 109, 98, 101, 114, 255, 5, 128, 161, 121, 129, 166, 110, 117, 109, 98, 101, 114, 2, 4, 14, 20, 50, 2 })

      assert_equal(1, joins)
      assert_equal("tok123", room.reconnection_token.reconnection_token)

      -- handshake received the BOUNDED slice: code(1) + token(7) +
      -- serializerId(7) + len varint(1) → 1-based offset 17, slice covers
      -- the 49 reflection bytes; the tagged sections after it were skipped
      -- without touching the serializer
      assert_equal(1, #calls.handshake)
      assert_equal(17, calls.handshake[1].offset)
      assert_equal(16 + 49, calls.handshake[1].len)

      -- acknowledged with JOIN_ROOM byte (+ null terminator for HTML5)
      assert_equal(1, #sent)
      assert_equal(string.char(10, 0), sent[1])

      -- plain full state: body starts right after the code byte
      feed({ 14, 128, 165, 104, 101, 108, 108, 111, 129, 42 })
      assert_equal(1, #calls.set_state)
      assert_equal(2, calls.set_state[1].offset)

      -- TIMED-modified patch (143 = 15 | 0x80): the 8-byte
      -- [uint32 sNow][uint32 inputSeq] prefix must be consumed
      feed({ 143, 64, 226, 1, 0, 7, 0, 0, 0, 129, 43 })
      assert_equal(1, #calls.patch)
      assert_equal(10, calls.patch[1].offset)
    end)

    it("JoinRoomReconnect", function()
      local room, _, calls, feed = make_room()

      local joins = 0
      local reconnects = 0
      room:on("join", function() joins = joins + 1 end)
      room:on("reconnect", function() reconnects = reconnects + 1 end)

      -- plain room: state reflection only, no trailing sections
      feed({ 10, 4, 116, 111, 107, 65, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114 })
      assert_equal(1, joins)
      assert_equal(0, reconnects)
      assert_equal(1, #calls.handshake)

      -- reconnect JOIN: zero-length reflection → no handshake, 'reconnect'
      feed({ 10, 4, 116, 111, 107, 66, 6, 115, 99, 104, 101, 109, 97, 0 })
      assert_equal(1, joins)
      assert_equal(1, reconnects)
      assert_equal(1, #calls.handshake)
      assert_equal("tokB", room.reconnection_token.reconnection_token)
    end)

    it("RequestFrameEncoding", function()
      local room, sent = make_room()

      room:request("move", 7, function() end)

      -- [21][requestId 0]['move' fixstr][msgpack 7]
      assert_equal(1, #sent)
      assert_equal(string.char(21, 0, 164, 109, 111, 118, 101, 7), sent[1])
    end)

    it("RequestResponseOutcomes", function()
      local room, _, _, feed = make_room()

      local responses = {}
      local errors = {}
      local reply = function(response, err)
        table.insert(responses, { response })
        table.insert(errors, { err })
      end

      -- ids mint from 0 in order
      room:request("a", nil, reply)
      room:request("b", nil, reply)
      room:request("c", nil, reply)
      room:request("d", nil, reply)

      feed({ 22, 0, 0, 42 })                                      -- OK, payload 42
      feed({ 22, 1, 0 })                                          -- OK, no payload
      feed({ 22, 2, 1, 164, 110, 111, 112, 101 })                 -- REJECTED, "nope"
      feed({ 22, 3, 2, 222, 0, 2, 164, 110, 97, 109, 101, 165, 69, 114, 114, 111, 114, 167, 109, 101, 115, 115, 97, 103, 101, 164, 98, 111, 111, 109 }) -- ERROR, {name,message}
      feed({ 22, 205, 231, 3, 0, 1 })                             -- unknown id 999 — ignored

      assert_equal(4, #responses)
      assert_equal(42, responses[1][1])
      assert_equal(nil, errors[1][1])
      assert_equal(nil, responses[2][1]) -- OK with no payload
      assert_equal(nil, errors[2][1])
      assert_equal("nope", errors[3][1])
      assert_equal("Error", errors[4][1].name)
      assert_equal("boom", errors[4][1].message)
    end)

    it("RejectAllPendingOnClose", function()
      local room, _, _, feed = make_room()

      local errors = {}
      room:request("a", nil, function(_, err) table.insert(errors, err) end)
      room:request("b", nil, function(_, err) table.insert(errors, err) end)

      room:_reject_all_pending_requests("connection closed before a response was received.")

      assert_equal(2, #errors)
      assert_equal("connection closed before a response was received.", errors[1])

      -- a late response for a rejected id is ignored
      feed({ 22, 0, 0, 42 })
      assert_equal(2, #errors)
    end)

  end)

end
