local deftest = require "deftest.deftest"
local schema_serializer = require "test.schema_serializer"
local room_protocol = require "test.room_protocol"
local quantized = require "test.quantized"
local input = require "test.input"
local predict = require "test.predict"
local fossil_delta = require "test.fossil_delta"
local delta_container = require "test.delta_container"
local client = require "test.client"
local auth = require "test.auth"
local http = require "test.http"

function init(self)

  deftest.add(schema_serializer)
  deftest.add(room_protocol)
  deftest.add(quantized)
  deftest.add(input)
  deftest.add(predict)
  deftest.add(client)
  -- deftest.add(auth)
  -- deftest.add(http)

  -- deftest.add(fossil_delta)
  -- deftest.add(delta_container)
  deftest.run({ coverage = { enabled = true } })
end

function final(self)
  -- Add finalization code here
  -- Remove this function if not needed
end

function update(self, dt)
  -- Add update code here
  -- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
  -- Add message-handling code here
  -- Remove this function if not needed
end

function on_input(self, action_id, action)
  -- Add input-handling code here
  -- Remove this function if not needed
end

function on_reload(self)
  -- Add reload-handling code here
  -- Remove this function if not needed
end
